import {test} from 'node:test';import assert from 'node:assert/strict';import {readFileSync,mkdtempSync,rmSync} from 'node:fs';import {spawn,execFileSync} from 'node:child_process';import {tmpdir} from 'node:os';import {join} from 'node:path';import {fileURLToPath} from 'node:url';import vm from 'node:vm';import net from 'node:net';
const root=fileURLToPath(new URL('../',import.meta.url));const catalog=JSON.parse(readFileSync(root+'docs/templates/reference-batch.json','utf8'));const brand=readFileSync(root+'public/assets/brand-settings.js','utf8');
function pixel(html,paused=false){const config=JSON.parse(html.match(/window\.HUB_PAGE=(.*?);window\.APP_CONFIG/s)[1]);const calls=[],listeners={};let ready;const document={querySelectorAll:()=>[],head:{append(){}},createElement:()=>({}),addEventListener:(n,f)=>(listeners[n]??=[]).push(f)};const window={HUB_TRACKING_CONSENT:paused?false:undefined,TV_PREVIEW:config.preview,TV_SETTINGS_READY:{then:f=>ready=f},fbq:(...a)=>calls.push(a),addEventListener:(n,f)=>window[n]=f};vm.runInNewContext(brand,{window,document,navigator:{doNotTrack:'1',globalPrivacyControl:true}});ready(config);window['tv:settings']({detail:config});return {config,calls,click(){for(const f of listeners.click||[])f({button:0,target:{closest:()=>({getAttribute:()=>null})}});}};}
for(const item of catalog)test(item.id+' has local styles/scripts, explicit branding and clean project downloads',()=>{
 const html=readFileSync(root+'resources/pages/'+item.id+'.html','utf8');assert.match(html,/data-hub-name/);assert.match(html,/data-hub-logo/);assert.match(html,/download-link/);
 assert.doesNotMatch(html,/p6y2sej|LANDING_CFG|fbq\(|fbevents|goog-gt-|chrome-extension:|on(?:click|load|error)=|\.apk["'?]/i);
 for(const s of html.matchAll(/<script[^>]*src="([^"]+)"/g))assert.ok(!s[1].startsWith('http'));
 for(const a of html.matchAll(/<a\b[^>]*class="[^"]*download-link[^>]*>/g))assert.match(a[0],/href="#download"/);
 const context={window:{}};vm.runInNewContext(readFileSync(root+'public/themes/'+item.id+'/reference-data.js','utf8'),context);assert.equal(context.window.HUB_REFERENCE.id,item.id);
 const ui=readFileSync(root+'app/console.html','utf8');assert.match(ui,new RegExp('name="allowedTemplates" value="'+item.id+'">'));
 const tenant=readFileSync(root+'app/tenant.html','utf8');assert.match(tenant,new RegExp('data-template="'+item.id+'" hidden'));
});
test('all imported templates: isolated rendering, permissions, brand defaults, Pixel and download redirect',async t=>{
 const dir=mkdtempSync(join(tmpdir(),'hub-ref-test-')),env={...process.env,HUB_DATA_DIR:dir,HUB_DEV:'1'};execFileSync('php',['bin/setup.php','--username=fixture','--password=Fixture-Reference-Only!'],{cwd:root,env,stdio:'pipe'});
 const port=await new Promise(resolve=>{const s=net.createServer();s.listen(0,'127.0.0.1',()=>{const p=s.address().port;s.close(()=>resolve(p));});});const base='http://127.0.0.1:'+port,child=spawn('php',['-S','127.0.0.1:'+port,'-t','public','router.php'],{cwd:root,env,stdio:['ignore','ignore','pipe']});let log='';child.stderr.on('data',b=>log+=b);t.after(async()=>{child.kill();await new Promise(r=>child.once('exit',r));rmSync(dir,{recursive:true,force:true});});
 for(let n=0;n<50;n++){try{await fetch(base);break;}catch{await new Promise(r=>setTimeout(r,40));}}
 async function req(path,ctx={},body){const r=await fetch(base+path,{redirect:'manual',method:body===undefined?'GET':'POST',headers:{Origin:base,...(ctx.cookie?{Cookie:ctx.cookie}:{}),...(ctx.csrf?{'X-CSRF-Token':ctx.csrf}:{}),'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});const text=await r.text();let json;try{json=JSON.parse(text);}catch{}return {status:r.status,headers:r.headers,text,json,cookie:r.headers.get('set-cookie')?.split(';')[0]||ctx.cookie};}
 const l=await req('/api/login',{}, {username:'fixture',password:'Fixture-Reference-Only!'});const master={cookie:l.cookie,csrf:l.json.csrf};const a=await req('/api/projects',master,{name:'Imported fixture',allowedTemplates:catalog.map(x=>x.id),template:catalog[0].id});assert.equal(a.status,200);const path='/p/'+a.json.project.slug;const c=await req(path+'/api/login',{},a.json.credentials);const tenant={cookie:c.cookie,csrf:c.json.csrf};
 const legacy=await req('/api/projects',master,{name:'Legacy fixture'});assert.deepEqual(legacy.json.project.allowedTemplates,['feiyue','dptv']);
 for(const item of catalog){await t.test(item.id+' actual, global/project previews and every download slot',async()=>{
  assert.equal((await req(path+'/api/settings',tenant,{template:item.id,pixelId:'1000000000000001',appName:'',logoData:'',downloadUrl:''})).status,200);
  const page=await req(path);assert.equal(page.status,200);const f=pixel(page.text);assert.equal(f.config.appName,item.brand);assert.equal(f.config.downloadUrl,path+'/dl');assert.deepEqual(f.calls,[['init','1000000000000001'],['track','PageView']]);
  const count=[...page.text.matchAll(/<a\b[^>]*class="[^"]*download-link[^>]*>/g)].length;assert.ok(count>0);for(let n=0;n<count;n++)f.click();assert.equal(f.calls.filter(x=>x[1]==='DownloadClick').length,count);assert.deepEqual(pixel(page.text,true).calls,[]);
  assert.equal((page.text.match(/src="\/assets\/brand-settings\.js/g)||[]).length,1);assert.equal((page.text.match(/src="\/assets\/collector\.js/g)||[]).length,1);
  assert.equal((await req(path+'/dl')).status,404);
  for(const url of ['/templates/'+item.id+'/preview',path+'/preview/'+item.id]){const r=await req(url,master);assert.equal(r.status,200);assert.deepEqual(pixel(r.text).calls,[]);assert.equal(pixel(r.text).config.token,'');}
  for(const [appName,logoData] of [['',''],['Custom Fixture',''],['','data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jY5kAAAAASUVORK5CYII='],['Custom Fixture','data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jY5kAAAAASUVORK5CYII=']]){await req(path+'/api/settings',tenant,{appName,logoData});const f=pixel((await req(path)).text);assert.equal(f.config.appName,appName||item.brand);assert.equal(f.config.logoData,logoData);}
  await req(path+'/api/settings',tenant,{pixelId:'',downloadUrl:'https://example.com/fixture.apk'});assert.deepEqual(pixel((await req(path)).text).calls,[]);const dl=await req(path+'/dl');assert.equal(dl.status,302);assert.equal(dl.headers.get('location'),'https://example.com/fixture.apk');
  assert.equal((await req('/themes/'+item.id+'/theme.css')).status,200);assert.equal((await req('/themes/'+item.id+'/reference-data.js')).status,200);
 });}
 const totals=(await req(path+'/api/dashboard',tenant)).json.stats.totals;assert.equal(totals.visits,0);
 await req('/api/projects/'+a.json.project.slug,master,{allowedTemplates:['feiyue']});for(const item of catalog){assert.equal((await req(path+'/preview/'+item.id,tenant)).status,403);assert.equal((await req(path+'/api/settings',tenant,{template:item.id})).status,403);}
 assert.doesNotMatch(log,/PHP (Warning|Fatal)|Landing Hub:/);
});
